name: CI - Client

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.5.2
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: client/pnpm-lock.yaml
          node-version: "22"
          cache: pnpm

      - name: Install Client Dependencies
        run: |
          cd client && pnpm install --frozen-lockfile

      - name: Prep for Vitest Browser Mode
        run: |
          cd client && pnpm exec playwright install
